# encoding=utf-8

lista_vereadores = [
{"nome": "ABOU ANNI", "artigo": "Abou_Anni", "id": "40502"},
{"nome": "ADILSON AMADEU", "artigo": "Adilson_Amadeu", "id": "40517"},
{"nome": "ADOLFO QUINTAS", "artigo": "Adolfo_Quintas", "id": "40514"},
{"nome": "AGNALDO TIMÓTEO", "artigo": "Agnaldo_Timóteo", "id": "40511"},
{"nome": "ALFREDINHO", "artigo": "Alfredinho", "id": "40527"},
{"nome": "ANTONIO CARLOS RODRIGUES", "artigo": "Antonio_Carlos_Rodrigues", "id": "40464"},
{"nome": "ANTONIO GOULART", "artigo": "Goulart", "id": "40433"},
{"nome": "ARSELINO TATTO", "artigo": "Arselino_Tatto", "id": "40364"},
{"nome": "ATÍLIO FRANCISCO", "artigo": "Atílio_Francisco", "id": "40468"},
{"nome": "AURÉLIO MIGUEL", "artigo": "Aurélio_Miguel", "id": "40499"},
{"nome": "CARLOS ALBERTO BEZERRA JR.", "artigo": "Carlos_Alberto_Bezerra_Jr.", "id": "40470"},
{"nome": "CARLOS APOLINÁRIO", "artigo": "Carlos_Apolinário", "id": "40473"},
{"nome": "CELSO JATENE", "artigo": "Celso_Jatene", "id": "40471"},
{"nome": "CHICO MACENA", "artigo": "Chico_Macena", "id": "40507"},
{"nome": "CLAUDINHO", "artigo": "Claudinho_de_Souza", "id": "40501"},
{"nome": "CLAUDIO FONSECA", "artigo": "Claudio_Fonseca", "id": "40474"},
{"nome": "CLAUDIO PRADO", "artigo": "Claudio_Prado", "id": "40518"},
{"nome": "DALTON SILVANO", "artigo": "Dalton_Silvano", "id": "40437"},
{"nome": "DOMINGOS DISSEI", "artigo": "Domingos_Dissiei", "id": "40438"},
{"nome": "DONATO", "artigo": "Donato", "id": "40519"},
{"nome": "DR. MILTON FERREIRA", "artigo": "Milton_Ferreira", "id": "40539"},
{"nome": "ELISEU GABRIEL", "artigo": "Eliseu_Gabriel", "id": "40475"},
{"nome": "FLORIANO PESARO", "artigo": "Floriano_Pesaro", "id": "40537"},
{"nome": "FRANCISCO CHAGAS", "artigo": "Francisco_Chagas", "id": "40491"},
{"nome": "GABRIEL CHALITA", "artigo": "Gabriel_Chalita", "id": "40536"},
{"nome": "GILBERTO NATALINI", "artigo": "Gilberto_Natalini", "id": "40476"},
{"nome": "GILSON BARRETO", "artigo": "Gilson_Barreto", "id": "40392"},
{"nome": "ITALO CARDOSO", "artigo": "Ítalo_Cardoso", "id": "40370"},
{"nome": "JAMIL MURAD", "artigo": "Jamil_Murad", "id": "40532"},
{"nome": "JOÃO ANTONIO", "artigo": "João_Antonio", "id": "40459"},
{"nome": "JOOJI HATO", "artigo": "Jooji_Hato", "id": "40331"},
{"nome": "JOSÉ AMÉRICO", "artigo": "José_Américo", "id": "40494"},
{"nome": "JULIANA CARDOSO", "artigo": "Juliana_Cardoso", "id": "40533"},
{"nome": "JUSCELINO", "artigo": "Juscelino", "id": "40520"},
{"nome": "KAMIA", "artigo": "Kamia", "id": "40385"},
{"nome": "MARA GABRILLI", "artigo": "Mara_Gabrilli", "id": "40528"},
{"nome": "MARCELO AGUIAR", "artigo": "Marcelo_Aguiar", "id": "40541"},
{"nome": "MARCO AURELIO CUNHA", "artigo": "Marco_Aurélio_Cunha", "id": "40534"},
{"nome": "MARTA COSTA", "artigo": "Marta_Costa", "id": "40504"},
{"nome": "MILTON LEITE", "artigo": "Milton_Leite", "id": "40446"},
{"nome": "MISSIONÁRIO JOSE OLIMPIO", "artigo": "José_Olímpio", "id": "40456"},
{"nome": "NETINHO", "artigo": "Netinho", "id": "40506"},
{"nome": "NETINHO DE PAULA", "artigo": "Netinho_de_Paula", "id": "40531"},
{"nome": "NOEMI NONATO", "artigo": "Noemi_Nonato", "id": "40510"},
{"nome": "PAULO FRANGE", "artigo": "Paulo_Frange", "id": "40449"},
{"nome": "PENNA", "artigo": "Penna", "id": "40540"},
{"nome": "QUITO FORMIGA", "artigo": "Quito_Formiga", "id": "40521"},
{"nome": "RICARDO TEIXEIRA", "artigo": "Ricardo_Teixeira", "id": "40529"},
{"nome": "ROBERTO TRIPOLI", "artigo": "Roberto_Tripoli", "id": "40374"},
{"nome": "SANDRA TADEU", "artigo": "Sandra_Tadeu", "id": "40535"},
{"nome": "SENIVAL MOURA", "artigo": "Senival", "id": "40524"},
{"nome": "SOUZA SANTOS", "artigo": "Souza_Santos", "id": "40538"},
{"nome": "TONINHO PAIVA", "artigo": "Toninho_Paiva", "id": "40403"},
{"nome": "WADIH MUTRAN", "artigo": "Wadih_Mutran", "id": "40345"},
{"nome": "ZELÃO", "artigo": "Zelão", "id": "40496"}
]
